// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCp8IGc7q89BV04i4_p6ISlm5iXmcLVvsk',
    appId: '1:742754622047:web:7010dd3a2cd15f625e19ea',
    messagingSenderId: '742754622047',
    projectId: 'scorify-f60fc',
    authDomain: 'scorify-f60fc.firebaseapp.com',
    storageBucket: 'scorify-f60fc.firebasestorage.app',
    measurementId: 'G-XRJ9MGDETB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYhKvxtp4F2r5Rn7oR0QGC-2vrpzsf_0Q',
    appId: '1:742754622047:android:ada6632540bc5d7f5e19ea',
    messagingSenderId: '742754622047',
    projectId: 'scorify-f60fc',
    storageBucket: 'scorify-f60fc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLg3AGO3N_h4VECHyQ9yT9pea6FgVaqZY',
    appId: '1:742754622047:ios:21ccbff6d95aa05e5e19ea',
    messagingSenderId: '742754622047',
    projectId: 'scorify-f60fc',
    storageBucket: 'scorify-f60fc.firebasestorage.app',
    iosBundleId: 'com.example.scorify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLg3AGO3N_h4VECHyQ9yT9pea6FgVaqZY',
    appId: '1:742754622047:ios:21ccbff6d95aa05e5e19ea',
    messagingSenderId: '742754622047',
    projectId: 'scorify-f60fc',
    storageBucket: 'scorify-f60fc.firebasestorage.app',
    iosBundleId: 'com.example.scorify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCp8IGc7q89BV04i4_p6ISlm5iXmcLVvsk',
    appId: '1:742754622047:web:efb469942a2287565e19ea',
    messagingSenderId: '742754622047',
    projectId: 'scorify-f60fc',
    authDomain: 'scorify-f60fc.firebaseapp.com',
    storageBucket: 'scorify-f60fc.firebasestorage.app',
    measurementId: 'G-CTZ8RWJXLL',
  );

}